#! /bin/sh
#
#	@(#)struct	4.2	(Berkeley)	83/12/19
#
#  Copyright (c) 1986 MIPS Computer Systems, Inc.
#  All Rights Reserved.
#
#  $Header: struct,v 1.1.1.1 89/11/26 15:09:12 wje Exp $
#
trap "rm -f /tmp/struct*$$" 0 1 2 3 13 15
files=no
for i
do
	case $i in
	-*)	;;
	*)	files=yes
	esac
done

case $files in
yes)
	/bsd43/usr/lib/struct/structure $* >/tmp/struct$$
	;;
no)
	cat >/tmp/structin$$
	/bsd43/usr/lib/struct/structure /tmp/structin$$ $* >/tmp/struct$$
esac &&
	/bsd43/usr/lib/struct/beautify</tmp/struct$$
