#define	accept	__accept
#define	ffs	__ffs
#define	getgroups	__getgroups
#define	listen	__listen
#define	setreuid	__setreuid
#define	setsockopt	__setsockopt
#define	vfork	__vfork
#define	authdes_create	__authdes_create
#define	authdes_getucred	__authdes_getucred
#define	authnone_create	__authnone_create
#define	authunix_create	__authunix_create
#define	authunix_create_default	__authunix_create_default
#define	bcopy	__bcopy
#define	bind	__bind
#define	bindresvport	__bindresvport
#define	blkclr	__blkclr
#define	bzero	__bzero
#define	callrpc	__callrpc
#define	clnt_broadcast	__clnt_broadcast
#define	clnt_create	__clnt_create
#define	clnt_pcreateerror	__clnt_pcreateerror
#define	clnt_perrno	__clnt_perrno
#define	clnt_perror	__clnt_perror
#define	clnt_spcreateerror	__clnt_spcreateerror
#define	clnt_sperrno	__clnt_sperrno
#define	clnt_sperror	__clnt_sperror
#define	clntraw_create	__clntraw_create
#define	clnttcp_create	__clnttcp_create
#define	clntudp_bufcreate	__clntudp_bufcreate
#define	clntudp_create	__clntudp_create
#define	clntudp_destroy	__clntudp_destroy
#define	closelog	__closelog
#define	connect	__connect
#define	dbm_close	__dbm_close
#define	dbm_delete	__dbm_delete
#define	dbm_fetch	__dbm_fetch
#define	dbm_firstkey	__dbm_firstkey
#define	dbm_forder	__dbm_forder
#define	dbm_nextkey	__dbm_nextkey
#define	dbm_open	__dbm_open
#define	dbm_store	__dbm_store
#define	dn_comp	__dn_comp
#define	dn_expand	__dn_expand
#define	dn_skipname	__dn_skipname
#define	dns_endhostent	__dns_endhostent
#define	dns_gethostbyaddr	__dns_gethostbyaddr
#define	dns_gethostbyname	__dns_gethostbyname
#define	dns_service	__dns_service
#define	dns_sethostent	__dns_sethostent
#define	endhostent	__endhostent
#define	endnetent	__endnetent
#define	endnetgrent	__endnetgrent
#define	endprotoent	__endprotoent
#define	endrpcent	__endrpcent
#define	endservent	__endservent
#define	ether_aton	__ether_aton
#define	ether_hostton	__ether_hostton
#define	ether_line	__ether_line
#define	ether_ntoa	__ether_ntoa
#define	ether_ntohost	__ether_ntohost
#define	flock	__flock
#define	fp_query	__fp_query
#define	get_myaddress	__get_myaddress
#define	getdomainname	__getdomainname
#define	getdtablesize	__getdtablesize
#define	gethostbyaddr	__gethostbyaddr
#define	gethostbyname	__gethostbyname
#define	gethostent	__gethostent
#define	gethostname	__gethostname
#define	getnetbyaddr	__getnetbyaddr
#define	getnetbyname	__getnetbyname
#define	getnetent	__getnetent
#define	getnetgrent	__getnetgrent
#define	getnetname	__getnetname
#define	getprotobyname	__getprotobyname
#define	getprotobynumber	__getprotobynumber
#define	getprotoent	__getprotoent
#define	getrpcbyname	__getrpcbyname
#define	getrpcbynumber	__getrpcbynumber
#define	getrpcent	__getrpcent
#define	getservbyname	__getservbyname
#define	getservbyport	__getservbyport
#define	getservent	__getservent
#define	getsockname	__getsockname
#define	gettimeofday	__gettimeofday
#define	host2netname	__host2netname
#define	hostalias	__hostalias
#define	ht_endgrent	__ht_endgrent
#define	ht_endhostent	__ht_endhostent
#define	ht_endnetent	__ht_endnetent
#define	ht_endnetgrent	__ht_endnetgrent
#define	ht_endprotoent	__ht_endprotoent
#define	ht_endpwent	__ht_endpwent
#define	ht_endrpcent	__ht_endrpcent
#define	ht_endservent	__ht_endservent
#define	ht_fgetgrent	__ht_fgetgrent
#define	ht_getgrent	__ht_getgrent
#define	ht_getgrgid	__ht_getgrgid
#define	ht_getgrnam	__ht_getgrnam
#define	ht_gethostbyaddr	__ht_gethostbyaddr
#define	ht_gethostbyname	__ht_gethostbyname
#define	ht_gethostent	__ht_gethostent
#define	ht_getnetbyaddr	__ht_getnetbyaddr
#define	ht_getnetbyname	__ht_getnetbyname
#define	ht_getnetent	__ht_getnetent
#define	ht_getnetgrent	__ht_getnetgrent
#define	ht_getprotobyname	__ht_getprotobyname
#define	ht_getprotobynumber	__ht_getprotobynumber
#define	ht_getprotoent	__ht_getprotoent
#define	ht_getpw	__ht_getpw
#define	ht_getpwent	__ht_getpwent
#define	ht_getpwnam	__ht_getpwnam
#define	ht_getpwuid	__ht_getpwuid
#define	ht_getrpcbyname	__ht_getrpcbyname
#define	ht_getrpcbynumber	__ht_getrpcbynumber
#define	ht_getrpcent	__ht_getrpcent
#define	ht_getservbyname	__ht_getservbyname
#define	ht_getservbyport	__ht_getservbyport
#define	ht_getservent	__ht_getservent
#define	ht_innetgr	__ht_innetgr
#define	ht_service	__ht_service
#define	ht_setgrent	__ht_setgrent
#define	ht_sethostent	__ht_sethostent
#define	ht_setnetent	__ht_setnetent
#define	ht_setnetgrent	__ht_setnetgrent
#define	ht_setprotoent	__ht_setprotoent
#define	ht_setpwent	__ht_setpwent
#define	ht_setrpcent	__ht_setrpcent
#define	ht_setservent	__ht_setservent
#define	htonl	__htonl
#define	htons	__htons
#define	index	__index
#define	inet_addr	__inet_addr
#define	inet_makeaddr	__inet_makeaddr
#define	inet_network	__inet_network
#define	inet_ntoa	__inet_ntoa
#define	innetgr	__innetgr
#define	key_decryptsession	__key_decryptsession
#define	key_encryptsession	__key_encryptsession
#define	key_gendes	__key_gendes
#define	key_setsecret	__key_setsecret
#define	netname2host	__netname2host
#define	netname2user	__netname2user
#define	next_serv	__next_serv
#define	no_service	__no_service
#define	ntohl	__ntohl
#define	ntohs	__ntohs
#define	openlog	__openlog
#define	ovbcopy	__ovbcopy
#define	p_cdname	__p_cdname
#define	p_class	__p_class
#define	p_query	__p_query
#define	p_rr	__p_rr
#define	p_type	__p_type
#define	pmap_getmaps	__pmap_getmaps
#define	pmap_getport	__pmap_getport
#define	pmap_rmtcall	__pmap_rmtcall
#define	pmap_set	__pmap_set
#define	pmap_unset	__pmap_unset
#define	putlong	__putlong
#define	putshort	__putshort
#define	rcmd	__rcmd
#define	recv	__recv
#define	recvfrom	__recvfrom
#define	registerrpc	__registerrpc
#define	res_init	__res_init
#define	res_mkquery	__res_mkquery
#define	res_query	__res_query
#define	res_querydomain	__res_querydomain
#define	res_search	__res_search
#define	res_send	__res_send
#define	rindex	__rindex
#define	rpc_perror	__rpc_perror
#define	rpc_perror1	__rpc_perror1
#define	rpc_perror2	__rpc_perror2
#define	rresvport	__rresvport
#define	rtime	__rtime
#define	ruserok	__ruserok
#define	select	__select
#define	send	__send
#define	sendto	__sendto
#define	setgrfile	__setgrfile
#define	setgrjunk	__setgrjunk
#define	sethostent	__sethostent
#define	sethostfile	__sethostfile
#define	setlogmask	__setlogmask
#define	setnetent	__setnetent
#define	setnetgrent	__setnetgrent
#define	setprotoent	__setprotoent
#define	setpwfile	__setpwfile
#define	setrpcent	__setrpcent
#define	setservent	__setservent
#define	socket	__socket
#define	strcasecmp	__strcasecmp
#define	strncasecmp	__strncasecmp
#define	svc_getreq	__svc_getreq
#define	svc_getreqset	__svc_getreqset
#define	svc_register	__svc_register
#define	svc_run	__svc_run
#define	svc_sendreply	__svc_sendreply
#define	svc_unregister	__svc_unregister
#define	svcerr_auth	__svcerr_auth
#define	svcerr_decode	__svcerr_decode
#define	svcerr_noproc	__svcerr_noproc
#define	svcerr_noprog	__svcerr_noprog
#define	svcerr_progvers	__svcerr_progvers
#define	svcerr_systemerr	__svcerr_systemerr
#define	svcerr_weakauth	__svcerr_weakauth
#define	svcfd_create	__svcfd_create
#define	svcraw_create	__svcraw_create
#define	svctcp_create	__svctcp_create
#define	svcudp_bufcreate	__svcudp_bufcreate
#define	svcudp_create	__svcudp_create
#define	svcudp_enablecache	__svcudp_enablecache
#define	syslog	__syslog
#define	user2netname	__user2netname
#define	usingypmap	__usingypmap
#define	v1prot_dofirst	__v1prot_dofirst
#define	v1prot_donext	__v1prot_donext
#define	vis_nextserv	__vis_nextserv
#define	xdr_accepted_reply	__xdr_accepted_reply
#define	xdr_array	__xdr_array
#define	xdr_authdes_cred	__xdr_authdes_cred
#define	xdr_authdes_verf	__xdr_authdes_verf
#define	xdr_authunix_parms	__xdr_authunix_parms
#define	xdr_bool	__xdr_bool
#define	xdr_bytes	__xdr_bytes
#define	xdr_callhdr	__xdr_callhdr
#define	xdr_callmsg	__xdr_callmsg
#define	xdr_char	__xdr_char
#define	xdr_cryptkeyarg	__xdr_cryptkeyarg
#define	xdr_cryptkeyres	__xdr_cryptkeyres
#define	xdr_datum	__xdr_datum
#define	xdr_des_block	__xdr_des_block
#define	xdr_deskey	__xdr_deskey
#define	xdr_double	__xdr_double
#define	xdr_enum	__xdr_enum
#define	xdr_float	__xdr_float
#define	xdr_free	__xdr_free
#define	xdr_getcredres	__xdr_getcredres
#define	xdr_int	__xdr_int
#define	xdr_keybuf	__xdr_keybuf
#define	xdr_keystatus	__xdr_keystatus
#define	xdr_long	__xdr_long
#define	xdr_netnamestr	__xdr_netnamestr
#define	xdr_netobj	__xdr_netobj
#define	xdr_opaque	__xdr_opaque
#define	xdr_opaque_auth	__xdr_opaque_auth
#define	xdr_pmap	__xdr_pmap
#define	xdr_pmaplist	__xdr_pmaplist
#define	xdr_pointer	__xdr_pointer
#define	xdr_reference	__xdr_reference
#define	xdr_rejected_reply	__xdr_rejected_reply
#define	xdr_replymsg	__xdr_replymsg
#define	xdr_rmtcall_args	__xdr_rmtcall_args
#define	xdr_rmtcallres	__xdr_rmtcallres
#define	xdr_short	__xdr_short
#define	xdr_string	__xdr_string
#define	xdr_u_char	__xdr_u_char
#define	xdr_u_int	__xdr_u_int
#define	xdr_u_long	__xdr_u_long
#define	xdr_u_short	__xdr_u_short
#define	xdr_union	__xdr_union
#define	xdr_unixcred	__xdr_unixcred
#define	xdr_vector	__xdr_vector
#define	xdr_void	__xdr_void
#define	xdr_wrapstring	__xdr_wrapstring
#define	xdr_yp_binding	__xdr_yp_binding
#define	xdr_yp_buf	__xdr_yp_buf
#define	xdr_yp_inaddr	__xdr_yp_inaddr
#define	xdr_ypall	__xdr_ypall
#define	xdr_ypbind_resp	__xdr_ypbind_resp
#define	xdr_ypbind_setdom	__xdr_ypbind_setdom
#define	xdr_ypdelete_args	__xdr_ypdelete_args
#define	xdr_ypdomain_wrap_string	__xdr_ypdomain_wrap_string
#define	xdr_ypmap_parms	__xdr_ypmap_parms
#define	xdr_ypmap_wrap_string	__xdr_ypmap_wrap_string
#define	xdr_ypmaplist	__xdr_ypmaplist
#define	xdr_ypmaplist_wrap_string	__xdr_ypmaplist_wrap_string
#define	xdr_ypowner_wrap_string	__xdr_ypowner_wrap_string
#define	xdr_yppushresp_xfr	__xdr_yppushresp_xfr
#define	xdr_ypreq_key	__xdr_ypreq_key
#define	xdr_ypreq_nokey	__xdr_ypreq_nokey
#define	xdr_ypreq_xfr	__xdr_ypreq_xfr
#define	xdr_ypresp_key_val	__xdr_ypresp_key_val
#define	xdr_ypresp_maplist	__xdr_ypresp_maplist
#define	xdr_ypresp_master	__xdr_ypresp_master
#define	xdr_ypresp_order	__xdr_ypresp_order
#define	xdr_ypresp_val	__xdr_ypresp_val
#define	xdr_ypupdate_args	__xdr_ypupdate_args
#define	xdrmem_create	__xdrmem_create
#define	xdrrec_create	__xdrrec_create
#define	xdrrec_endofrecord	__xdrrec_endofrecord
#define	xdrrec_eof	__xdrrec_eof
#define	xdrrec_skiprecord	__xdrrec_skiprecord
#define	xdrstdio_create	__xdrstdio_create
#define	xprt_register	__xprt_register
#define	xprt_unregister	__xprt_unregister
#define	yp_all	__yp_all
#define	yp_bind	__yp_bind
#define	yp_endgrent	__yp_endgrent
#define	yp_endhostent	__yp_endhostent
#define	yp_endnetent	__yp_endnetent
#define	yp_endnetgrent	__yp_endnetgrent
#define	yp_endprotoent	__yp_endprotoent
#define	yp_endpwent	__yp_endpwent
#define	yp_endrpcent	__yp_endrpcent
#define	yp_endservent	__yp_endservent
#define	yp_fgetgrent	__yp_fgetgrent
#define	yp_first	__yp_first
#define	yp_get_default_domain	__yp_get_default_domain
#define	yp_getgrent	__yp_getgrent
#define	yp_getgrgid	__yp_getgrgid
#define	yp_getgrnam	__yp_getgrnam
#define	yp_gethostbyaddr	__yp_gethostbyaddr
#define	yp_gethostbyname	__yp_gethostbyname
#define	yp_gethostent	__yp_gethostent
#define	yp_getnetbyaddr	__yp_getnetbyaddr
#define	yp_getnetbyname	__yp_getnetbyname
#define	yp_getnetent	__yp_getnetent
#define	yp_getnetgrent	__yp_getnetgrent
#define	yp_getprotobyname	__yp_getprotobyname
#define	yp_getprotobynumber	__yp_getprotobynumber
#define	yp_getprotoent	__yp_getprotoent
#define	yp_getpwent	__yp_getpwent
#define	yp_getpwnam	__yp_getpwnam
#define	yp_getpwuid	__yp_getpwuid
#define	yp_getrpcbyname	__yp_getrpcbyname
#define	yp_getrpcbynumber	__yp_getrpcbynumber
#define	yp_getrpcent	__yp_getrpcent
#define	yp_getservbyname	__yp_getservbyname
#define	yp_getservbyport	__yp_getservbyport
#define	yp_getservent	__yp_getservent
#define	yp_innetgr	__yp_innetgr
#define	yp_master	__yp_master
#define	yp_match	__yp_match
#define	yp_next	__yp_next
#define	yp_order	__yp_order
#define	yp_service	__yp_service
#define	yp_setgrent	__yp_setgrent
#define	yp_sethostent	__yp_sethostent
#define	yp_sethostfile	__yp_sethostfile
#define	yp_setnetent	__yp_setnetent
#define	yp_setnetgrent	__yp_setnetgrent
#define	yp_setprotoent	__yp_setprotoent
#define	yp_setpwent	__yp_setpwent
#define	yp_setpwfile	__yp_setpwfile
#define	yp_setrpcent	__yp_setrpcent
#define	yp_setservent	__yp_setservent
#define	yp_unbind	__yp_unbind
#define	yp_update	__yp_update
#define	yperr_string	__yperr_string
#define	ypprot_err	__ypprot_err
