/*
 * |-----------------------------------------------------------|
 * | Copyright (c) 1990 MIPS Computer Systems, Inc.            |
 * | All Rights Reserved                                       |
 * |-----------------------------------------------------------|
 * |          Restricted Rights Legend                         |
 * | Use, duplication, or disclosure by the Government is      |
 * | subject to restrictions as set forth in                   |
 * | subparagraph (c)(1)(ii) of the Rights in Technical        |
 * | Data and Computer Software Clause of DFARS 52.227-7013.   |
 * |         MIPS Computer Systems, Inc.                       |
 * |         928 Arques Avenue                                 |
 * |         Sunnyvale, CA 94086                               |
 * |-----------------------------------------------------------|
 */
#ident	"$Header: rules.c,v 1.5.2.2 90/05/09 16:45:17 wje Exp $"
#include "defs"
/*
 * DEFAULT RULES FOR UNIX at Mips Computer Systems
 *
 * This is currently the concatation of the rules from system 5 and 4.2bsd
 * make's with the addition a few macros used for version control at Mips.
 *
 */

/*
 *	These are the internal rules that "make" trucks around with it at
 *	all times. One could completely delete this entire list and just
 *	conventionally define a global "include" makefile which had these
 *	rules in it. That would make the rules dynamically changeable
 *	without recompiling make. This file has been modified for local
 *	needs. There are currently three versions of this file with the
 *	source; namely, rules.c (which is the version running in Columbus),
 *	pwbrules.c which is an attempt at satisfying the requirements
 *	of PWB systems and mipsrules.c the local rules at Mips Computer Systems.
 *	The makefile for make (Makefile) is parameterized for a different
 *	rules file. The macro $(RULES) defined in "Makefile" can be set
 *	to another file and when "make" is "made" the procedure will
 *	use the new file. The recommended way to do this is on the
 *	command line as follows:
 *		"make -f make.mk RULES=pwbrules"
 */

CHARSTAR builtin[] =
	{
	".SUFFIXES: .out .o .u .c .c~ .p .p~ .f .f~ .F .F~ .e .e~ .r .r~ .y .y~ .l .l~ .s .s~ .sh .sh~ .h .h~ .cl .cl~ .cob .cob~ .pl1 .pl1~ .pli .pli~",

/* PRESET VARIABLES */
	"MAKE=make",
	"LOADLIBS=",
	"YACC=yacc",
	"YFLAGS=",
	"LEX=lex",
	"LFLAGS=",
	"LD=ld",
	"MLD=mld",
	"LDFLAGS=",
	"CC=cc",
	"MCC=mcc",
	"CFLAGS=",
	"PC=pc",
	"MPC=mpc",
	"PFLAGS=",
	"FC=f77",
	"MFC=mf77",
	"FFLAGS=",
	"EFLAGS=",
	"RFLAGS=",
	"AS=as",
	"MAS=mas",
	"ASFLAGS=",
	"COB=cobol",
	"COBFLAGS=",
	"PL1=pl1",
	"PL1FLAGS=",
	"GET=get",
	"GFLAGS=",
	"AR=ar",
	"MAR=mar",
	"GETVER=getver",
	"GVFLAGS=",
	"DELTAVER=deltaver",
	"DVFLAGS=",
	"VERS=vers",
	"VFILE=s.$(VERS).c",
	"INSTALL=install",

/* SINGLE SUFFIX RULES */
	".c:",
		"\t$(CC) $(CFLAGS) $< $(LDFLAGS) -o $@",
	".c~:",
		"\t$(GET) $(GFLAGS) -p $< > $*.c",
		"\t$(CC) $(CFLAGS) $*.c $(LDFLAGS) -o $*",
		"\t-rm -f $*.c",
	".p:",
		"\t$(PC) $(PFLAGS) $< $(LDFLAGS) -o $@",
	".p~:",
		"\t$(GET) $(GFLAGS) -p $< > $*.p",
		"\t$(PC) $(PFLAGS) $*.p $(LDFLAGS) -o $*",
		"\t-rm -f $*.p",
	".f:",
		"\t$(FC) $(FFLAGS) $< $(LDFLAGS) -o $@",
	".f~:",
		"\t$(GET) $(GFLAGS) -p $< > $*.f",
		"\t$(FC) $(FFLAGS) $*.f $(LDFLAGS) -o $*",
		"\t-rm -f $*.f",
	".F:",
		"\t$(FC) $(FFLAGS) $< $(LDFLAGS) -o $@",
	".F~:",
		"\t$(GET) $(GFLAGS) -p $< > $*.F",
		"\t$(FC) $(FFLAGS) $*.F $(LDFLAGS) -o $*",
		"\t-rm -f $*.F",
	".sh:",
		"\tcp $< $@; chmod 0777 $@",
	".sh~:",
		"\t$(GET) $(GFLAGS) -p $< > $*.sh",
		"\tcp $*.sh $*; chmod 0777 $@",
		"\t-rm -f $*.sh",

/* DOUBLE SUFFIX RULES */
	".c.o:",
		"\t$(CC) $(CFLAGS) -c $<",
	".c~.o:",
		"\t$(GET) $(GFLAGS) -p $< > $*.c",
		"\t$(CC) $(CFLAGS) -c $*.c",
		"\t-rm -f $*.c",
	".c~.c:",
		"\t$(GET) $(GFLAGS) -p $< > $*.c",
	".c.u:",
		"\t$(CC) $(CFLAGS) -j $<",
	".c~.u:",
		"\t$(GET) $(GFLAGS) -p $< > $*.c",
		"\t$(CC) $(CFLAGS) -j $*.c",
		"\t-rm -f $*.c",
	".c~.c:",
		"\t$(GET) $(GFLAGS) -p $< > $*.c",
	".p.o:",
		"\t$(PC) $(PFLAGS) -c $<",
	".p~.o:",
		"\t$(GET) $(GFLAGS) -p $< > $*.p",
		"\t$(PC) $(PFLAGS) -c $*.p",
		"\t-rm -f $*.p",
	".p.u:",
		"\t$(PC) $(PFLAGS) -j $<",
	".p~.u:",
		"\t$(GET) $(GFLAGS) -p $< > $*.p",
		"\t$(PC) $(PFLAGS) -j $*.p",
		"\t-rm -f $*.p",
	".p~.p:",
		"\t$(GET) $(GFLAGS) -p $< > $*.p",
	".f.o:",
		"\t$(FC) $(FFLAGS) -c $<",
	".f~.o:",
		"\t$(GET) $(GFLAGS) -p $< > $*.f",
		"\t$(FC) $(FFLAGS) -c $*.f",
		"\t-rm -f $*.f",
	".f.u:",
		"\t$(FC) $(FFLAGS) -j $<",
	".f~.u:",
		"\t$(GET) $(GFLAGS) -p $< > $*.f",
		"\t$(FC) $(FFLAGS) -j $*.f",
		"\t-rm -f $*.f",
	".f~.f:",
		"\t$(GET) $(GFLAGS) -p $< > $*.f",
	".F.o:",
		"\t$(FC) $(FFLAGS) -c $<",
	".F~.o:",
		"\t$(GET) $(GFLAGS) -p $< > $*.F",
		"\t$(FC) $(FFLAGS) -c $*.F",
		"\t-rm -f $*.F",
	".F.u:",
		"\t$(FC) $(FFLAGS) -j $<",
	".F~.u:",
		"\t$(GET) $(GFLAGS) -p $< > $*.F",
		"\t$(FC) $(FFLAGS) -j $*.F",
		"\t-rm -f $*.F",
	".F~.F:",
		"\t$(GET) $(GFLAGS) -p $< > $*.F",
	".u.o:",
		"\t$(CC) $(CFLAGS) -c $<",
	".s.o:",
		"\t$(AS) $(ASFLAGS) -o $@ $<",
	".s~.o:",
		"\t$(GET) $(GFLAGS) -p $< > $*.s",
		"\t$(AS) $(ASFLAGS) -o $*.o $*.s",
		"\t-rm -f $*.s",
	".y.o:",
		"\t$(YACC) $(YFLAGS) $<",
		"\t$(CC) $(CFLAGS) -c y.tab.c",
		"\trm y.tab.c",
		"\tmv y.tab.o $@",
	".y~.o:",
		"\t$(GET) $(GFLAGS) -p $< > $*.y",
		"\t$(YACC) $(YFLAGS) $*.y",
		"\t$(CC) $(CFLAGS) -c y.tab.c",
		"\trm -f y.tab.c $*.y",
		"\tmv y.tab.o $*.o",
	".l.o:",
		"\t$(LEX) $(LFLAGS) $<",
		"\t$(CC) $(CFLAGS) -c lex.yy.c",
		"\trm lex.yy.c",
		"\tmv lex.yy.o $@",
	".l~.o:",
		"\t$(GET) $(GFLAGS) -p $< > $*.l",
		"\t$(LEX) $(LFLAGS) $*.l",
		"\t$(CC) $(CFLAGS) -c lex.yy.c",
		"\trm -f lex.yy.c $*.l",
		"\tmv lex.yy.o $*.o",
	".y.c :",
		"\t$(YACC) $(YFLAGS) $<",
		"\tmv y.tab.c $@",
	".y~.c :",
		"\t$(GET) $(GFLAGS) -p $< > $*.y",
		"\t$(YACC) $(YFLAGS) $*.y",
		"\tmv y.tab.c $*.c",
		"\t-rm -f $*.y",
	".l.c :",
		"\t$(LEX) $<",
		"\tmv lex.yy.c $@",
	".c.a:",
		"\t$(CC) -c $(CFLAGS) $<",
		"\t$(AR) rv $@ $*.o",
		"\trm -f $*.o",
	".c~.a:",
		"\t$(GET) $(GFLAGS) -p $< > $*.c",
		"\t$(CC) -c $(CFLAGS) $*.c",
		"\t$(AR) rv $@ $*.o",
		"\trm -f $*.[co]",
	".c.b:",
		"\t$(CC) -j $(CFLAGS) $<",
		"\t$(AR) rv $@ $*.u",
		"\trm -f $*.u",
	".c~.b:",
		"\t$(GET) $(GFLAGS) -p $< > $*.c",
		"\t$(CC) -j $(CFLAGS) $*.c",
		"\t$(AR) rv $@ $*.u",
		"\trm -f $*.[cu]",
	".p.a:",
		"\t$(PC) -c $(PFLAGS) $<",
		"\t$(AR) rv $@ $*.o",
		"\trm -f $*.o",
	".p~.a:",
		"\t$(GET) $(GFLAGS) -p $< > $*.p",
		"\t$(PC) -c $(PFLAGS) $*.p",
		"\t$(AR) rv $@ $*.o",
		"\trm -f $*.[po]",
	".p.b:",
		"\t$(PC) -j $(PFLAGS) $<",
		"\t$(AR) rv $@ $*.u",
		"\trm -f $*.u",
	".p~.b:",
		"\t$(GET) $(GFLAGS) -p $< > $*.p",
		"\t$(PC) -j $(PFLAGS) $*.p",
		"\t$(AR) rv $@ $*.u",
		"\trm -f $*.[pu]",
	".f.a:",
		"\t$(FC) -c $(FFLAGS) $<",
		"\t$(AR) rv $@ $*.o",
		"\trm -f $*.o",
	".f~.a:",
		"\t$(GET) $(GFLAGS) -p $< > $*.f",
		"\t$(FC) -c $(FFLAGS) $*.f",
		"\t$(AR) rv $@ $*.o",
		"\trm -f $*.[fo]",
	".f.b:",
		"\t$(FC) -j $(FFLAGS) $<",
		"\t$(AR) rv $@ $*.u",
		"\trm -f $*.u",
	".f~.b:",
		"\t$(GET) $(GFLAGS) -p $< > $*.f",
		"\t$(FC) -j $(FFLAGS) $*.f",
		"\t$(AR) rv $@ $*.u",
		"\trm -f $*.[fu]",
	".F.a:",
		"\t$(FC) -c $(FFLAGS) $<",
		"\t$(AR) rv $@ $*.o",
		"\trm -f $*.o",
	".F~.a:",
		"\t$(GET) $(GFLAGS) -p $< > $*.F",
		"\t$(FC) -c $(FFLAGS) $*.F",
		"\t$(AR) rv $@ $*.o",
		"\trm -f $*.[fo]",
	".F.b:",
		"\t$(FC) -j $(FFLAGS) $<",
		"\t$(AR) rv $@ $*.u",
		"\trm -f $*.u",
	".F~.b:",
		"\t$(GET) $(GFLAGS) -p $< > $*.F",
		"\t$(FC) -j $(FFLAGS) $*.F",
		"\t$(AR) rv $@ $*.u",
		"\trm -f $*.[fu]",
	".s.a:",
		"\t$(AS) $(ASFLAGS) -o $*.o $<",
		"\t$(AR) rv $@ $*.o",
		"\t-rm -f $*.o",
	".s~.a:",
		"\t$(GET) $(GFLAGS) -p $< > $*.s",
		"\t$(AS) $(ASFLAGS) -o $*.o $*.s",
		"\t$(AR) rv $@ $*.o",
		"\t-rm -f $*.[so]",
	".h~.h:",
		"\t$(GET) $(GFLAGS) -p $< > $*.h",
/*****************************************************************************
	"markfile.o:	markfile",
		"\tA=@;echo \"static char _sccsid[] = \\042`grep $$A'(#)' markfile`\\042;\" > markfile.c",
		"\tcc -c markfile.c",
		"\trm -f markfile.c",
*****************************************************************************/
/* 4.2bsd .x.out: rules (no .x~.out: rules added at this time) */
	".l.out:",
		"\t$(LEX) $(LFLAGS) $<",
		"\t$(CC) $(CFLAGS) lex.yy.c $(LOADLIBES) -ll -o $@",
		"\trm lex.yy.c",
	".y.out:",
		"\t$(YACC) $(YFLAGS) $<",
		"\t$(CC) $(CFLAGS) y.tab.c $(LOADLIBES) -ly -o $@",
		"\trm y.tab.c",
	".e.out:",
		"\t$(FC) $(EFLAGS) $(RFLAGS) $(FFLAGS) $< $(LOADLIBES) -o $@",
		"\t-rm $*.o",
	".r.out:",
		"\t$(FC) $(EFLAGS) $(RFLAGS) $(FFLAGS) $< $(LOADLIBES) -o $@",
		"\t-rm $*.o",
	".f.out:",
		"\t$(FC) $(EFLAGS) $(RFLAGS) $(FFLAGS) $< $(LOADLIBES) -o $@",
		"\t-rm $*.o",
	".F.out:",
		"\t$(FC) $(EFLAGS) $(RFLAGS) $(FFLAGS) $< $(LOADLIBES) -o $@",
		"\t-rm $*.o",
	".o.out:",
		"\t$(CC) $(CFLAGS) $< $(LOADLIBES) -o $@",
	".c.out:",
		"\t$(CC) $(CFLAGS) $< $(LOADLIBES) -o $@",
	".s.out:",
		"\t$(CC) $(CFLAGS) $< $(LOADLIBES) -o $@",
/* 4.2bsd .x.o: rules.  An .x~.o: has been added for each. */
	".r.o:",
		"\t$(FC) $(RFLAGS) $(EFLAGS) $(FFLAGS) -c $<",
	".r~.o:",
		"\t$(GET) $(GFLAGS) -p $< > $*.r",
		"\t$(FC) $(RFLAGS) $(EFLAGS) $(FFLAGS) -c $*.r",
		"\t-rm -f $*.r",
	".e.o:",
		"\t$(FC) $(RFLAGS) $(EFLAGS) $(FFLAGS) -c $<",
	".e~.o:",
		"\t$(GET) $(GFLAGS) -p $< > $*.e",
		"\t$(FC) $(RFLAGS) $(EFLAGS) $(FFLAGS) -c $*.e",
		"\t-rm -f $*.e",
	".cl.o:",
		"\tclass -c $<",
	".cl~.o:",
		"\t$(GET) $(GFLAGS) -p $< > $*.cl",
		"\tclass -c $*.cl",
		"\t-rm -f $*.cl",

/*  COBOL defaults   */

	".cob.out:",
		"\t$(COB) $(COBFLAGS) $< $(LOADLIBES) -o $@",

	".cob~.b:",
		"\t$(GET) $(GFLAGS) -p $< > $*.cob",
		"\t$(COB) -j $(COBFLAGS) $*.cob",
		"\t$(AR) rv $@ $*.u",
		"\trm -f $*.u $*.cob",

	".cob.b:",
		"\t$(COB) -j $(COBFLAGS) $<",
		"\t$(AR) rv $@ $*.u",
		"\trm -f $*.u",

	".cob~.a:",
		"\t$(GET) $(GFLAGS) -p $< > $*.cob",
		"\t$(COB) -c $(COBFLAGS) $*.cob",
		"\t$(AR) rv $@ $*.o",
		"\trm -f $*.cob $*.o",

	".cob.a:",
		"\t$(COB) -c $(COBFLAGS) $<",
		"\t$(AR) rv $@ $*.o",
		"\trm -f $*.o",

	".cob~.u:",
		"\t$(GET) $(GFLAGS) -p $< > $*.cob",
		"\t$(COB) $(COBFLAGS) -j $*.cob",
		"\t-rm -f $*.cob",

	".cob.u:",
		"\t$(COB) $(COBFLAGS) -j $<",

	".cob~.cob:",
		"\t$(GET) $(GFLAGS) -p $< > $*.cob",

	".cob~.o:",
		"\t$(GET) $(GFLAGS) -p $< > $*.cob",
		"\t$(COB) $(COBFLAGS) -c $*.cob",
		"\t-rm -f $*.cob",

	".cob.o:",
		"\t$(COB) $(COBFLAGS) -c $<",

	".cob~:",
		"\t$(GET) $(GFLAGS) -p $< > $*.cob",
		"\t$(COB) $(COBFLAGS) $(LDFLAGS) $*.cob -o $*",
		"\t-rm -f $*.cob",

	".cob:",
		"\t$(COB) $(COBFLAGS) $(LDFLAGS) $< -o $@",

/* PL1 defaults  */

	".pl1.out:",
		"\t$(PL1) $(PL1FLAGS) $< $(LOADLIBES) -o $@",

	".pli.out:",
		"\t$(PL1) $(PL1FLAGS) $< $(LOADLIBES) -o $@",

	".pli~.b:",
		"\t$(GET) $(GFLAGS) -p $< > $*.pli",
		"\t$(PL1) -j $(PL1FLAGS) $*.pli",
		"\t$(AR) rv $@ $*.u",
		"\trm -f $*.u $*.pli",

	".pli~.b:",
		"\t$(GET) $(GFLAGS) -p $< > $*.pli",
		"\t$(PL1) -j $(PL1FLAGS) $*.pli",
		"\t$(AR) rv $@ $*.u",
		"\trm -f $*.u $*.pli",

	".pl1~.b:",
		"\t$(GET) $(GFLAGS) -p $< > $*.pl1",
		"\t$(PL1) -j $(PL1FLAGS) $*.pl1",
		"\t$(AR) rv $@ $*.u",
		"\trm -f $*.u $*.pl1",

	".pli.b:",
		"\t$(PL1) -j $(PL1FLAGS) $<",
		"\t$(AR) rv $@ $*.u",
		"\trm -f $*.u",

	".pl1.b:",
		"\t$(PL1) -j $(PL1FLAGS) $<",
		"\t$(AR) rv $@ $*.u",
		"\trm -f $*.u",

	".pli~.a:",
		"\t$(GET) $(GFLAGS) -p $< > $*.pli",
		"\t$(PL1) -c $(PL1FLAGS) $*.pli",
		"\t$(AR) rv $@ $*.o",
		"\trm -f $*.pli $*.o",

	".pl1~.a:",
		"\t$(GET) $(GFLAGS) -p $< > $*.pl1",
		"\t$(PL1) -c $(PL1FLAGS) $*.pl1",
		"\t$(AR) rv $@ $*.o",
		"\trm -f $*.pl1 $*.o",

	".pli.a:",
		"\t$(PL1) -c $(PL1FLAGS) $<",
		"\t$(AR) rv $@ $*.o",
		"\trm -f $*.o",

	".pl1.a:",
		"\t$(PL1) -c $(PL1FLAGS) $<",
		"\t$(AR) rv $@ $*.o",
		"\trm -f $*.o",

	".pli~.u:",
		"\t$(GET) $(GFLAGS) -p $< > $*.pli",
		"\t$(PL1) $(PL1FLAGS) -j $*.pli",
		"\t-rm -f $*.pli",

	".pli~.u:",
		"\t$(GET) $(GFLAGS) -p $< > $*.pli",
		"\t$(PL1) $(PL1FLAGS) -j $*.pli",
		"\t-rm -f $*.pli",

	".pl1~.u:",
		"\t$(GET) $(GFLAGS) -p $< > $*.pl1",
		"\t$(PL1) $(PL1FLAGS) -j $*.pl1",
		"\t-rm -f $*.pl1",

	".pli.u:",
		"\t$(PL1) $(PL1FLAGS) -j $<",

	".pl1.u:",
		"\t$(PL1) $(PL1FLAGS) -j $<",

	".pli~.pli:",
		"\t$(GET) $(GFLAGS) -p $< > $*.pli",

	".pl1~.pl1:",
		"\t$(GET) $(GFLAGS) -p $< > $*.pl1",

	".pli~.o:",
		"\t$(GET) $(GFLAGS) -p $< > $*.pli",
		"\t$(PL1) $(PL1FLAGS) -c $*.pli",
		"\t-rm -f $*.pli",

	".pl1~.o:",
		"\t$(GET) $(GFLAGS) -p $< > $*.pl1",
		"\t$(PL1) $(PL1FLAGS) -c $*.pl1",
		"\t-rm -f $*.pl1",

	".pli.o:",
		"\t$(PL1) $(PL1FLAGS) -c $<",

	".pl1.o:",
		"\t$(PL1) $(PL1FLAGS) -c $<",

	".pli~:",
		"\t$(GET) $(GFLAGS) -p $< > $*.pli",
		"\t$(PL1) $(PL1FLAGS) $(LDFLAGS) $*.pli -o $*",
		"\t-rm -f $*.pli",

	".pl1~:",
		"\t$(GET) $(GFLAGS) -p $< > $*.pl1",
		"\t$(PL1) $(PL1FLAGS) $(LDFLAGS) $*.pl1 -o $*",
		"\t-rm -f $*.pl1",

	".pli:",
		"\t$(PL1) $(PL1FLAGS) $(LDFLAGS) $< -o $@",

	".pl1:",
		"\t$(PL1) $(PL1FLAGS) $(LDFLAGS) $< -o $@",

		0 };
