/*
 * |-----------------------------------------------------------|
 * | Copyright (c) 1990 MIPS Computer Systems, Inc.            |
 * | All Rights Reserved                                       |
 * |-----------------------------------------------------------|
 * |          Restricted Rights Legend                         |
 * | Use, duplication, or disclosure by the Government is      |
 * | subject to restrictions as set forth in                   |
 * | subparagraph (c)(1)(ii) of the Rights in Technical        |
 * | Data and Computer Software Clause of DFARS 52.227-7013.   |
 * |         MIPS Computer Systems, Inc.                       |
 * |         928 Arques Avenue                                 |
 * |         Sunnyvale, CA 94086                               |
 * |-----------------------------------------------------------|
 */
#ident	"$Header: ypupdate_xdr.c,v 1.1.1.2 90/05/07 21:32:36 wje Exp $"
#include <rpc/rpc.h>
#include <rpcsvc/ypupdate_prot.h>
/*
 * Compiled from ypupdate_prot.x using rpcgen
 * This is NOT source code!
 * DO NOT EDIT THIS FILE!
 */


bool_t
xdr_yp_buf(xdrs, objp)
	XDR *xdrs;
	yp_buf *objp;
{
	if (!xdr_bytes(xdrs, (char **)&objp->yp_buf_val, (u_int *)&objp->yp_buf_len, MAXYPDATALEN)) {
		return (FALSE);
	}
	return (TRUE);
}




bool_t
xdr_ypupdate_args(xdrs, objp)
	XDR *xdrs;
	ypupdate_args *objp;
{
	if (!xdr_string(xdrs, &objp->mapname, MAXMAPNAMELEN)) {
		return (FALSE);
	}
	if (!xdr_yp_buf(xdrs, &objp->key)) {
		return (FALSE);
	}
	if (!xdr_yp_buf(xdrs, &objp->datum)) {
		return (FALSE);
	}
	return (TRUE);
}




bool_t
xdr_ypdelete_args(xdrs, objp)
	XDR *xdrs;
	ypdelete_args *objp;
{
	if (!xdr_string(xdrs, &objp->mapname, MAXMAPNAMELEN)) {
		return (FALSE);
	}
	if (!xdr_yp_buf(xdrs, &objp->key)) {
		return (FALSE);
	}
	return (TRUE);
}


