#! /bin/sh
#
# Set up the timezone files.
#
# The file /etc/zoneinfo/uncompiled is supplied with each new system
# release.  If the file exists, the timezone files are recompiled
# and the file is removed.
#
# If there is no file called /etc/zoneinfo/localtime, the timezone
# is set to "US/Pacific" and the user is pointed to the manual page
# for further instructions.
#
# $Header: tzsetup,v 1.3.2.2 90/01/25 14:38:19 wje Exp $

PATH=/bin:/usr/bin:/etc

case "$1" in
'start')
	if [ -f /etc/zoneinfo/uncompiled ]
	then
		/etc/zic /etc/zoneinfo/SOURCES/* >/dev/null 2>&1
		rm -f /etc/zoneinfo/uncompiled
	fi
	if [ ! -f /etc/zoneinfo/localtime ]
	then
		zic -l "US/Pacific"
		echo "Timezone set to US/Pacific.  See zic(1m) for details"
	fi
	;;

'stop')
	;;

*)
	echo "usage: /etc/init.d/tzsetup {start|stop}"
	;;
esac
exit 0
