# $Header: Makefile.proto,v 1.3.1.2 89/12/16 22:34:00 wje Locked $
#
# Revision 4.3.1.2  85/05/13  17:21:18  lwall
# System V make needs space before line-continuing backslash.
# 
# Revision 4.3.1.1  85/05/10  11:30:15  lwall
# Branch for patches.
# 
# Revision 4.3  85/05/01  11:33:26  lwall
# Baseline for release with 4.3bsd.
# 

CC = cc
rnbin = ${DESTDIR}/usr/new
rnlib = ${DESTDIR}/usr/new/lib/news/rn
mansrc = ${DESTDIR}/usr/man/u_man/man1
manext = 1
CSYSTYPE=-systype bsd43
CFLAGS =  $(CSYSTYPE) -O $(ECFLAGS)
LDFLAGS = $(CSYSTYPE) $(ELDFLAGS)
NDIRC = 
NDIRO = 

libs =  -lcurses 

public = rn newsetup newsgroups Pnews Rnmail
private = norm.saver mbox.saver ng.help art.help pager.help subs.help makedir filexp Pnews.header
manpages = rn.1 Pnews.1 Rnmail.1 newsetup.1 newsgroups.1
util = Makefile makedepend newsnews

h1 = addng.h art.h artio.h artsrch.h backpage.h bits.h cheat.h common.h
h2 = final.h head.h help.h init.h intrp.h kfile.h last.h ndir.h ng.h
h3 = ngdata.h ngsrch.h ngstuff.h only.h rcln.h rcstuff.h
h4 = respond.h rn.h search.h sw.h term.h util.h

h = $(h1) $(h2) $(h3) $(h4)

c1 = addng.c art.c artio.c artsrch.c backpage.c bits.c cheat.c
c2 = final.c head.c help.c init.c intrp.c kfile.c last.c $(NDIRC) ng.c
c3 = ngdata.c ngsrch.c ngstuff.c only.c rcln.c rcstuff.c
c4 = respond.c rn.c search.c sw.c term.c util.c

c = $(c1) $(c2) $(c3) $(c4)

obj1 = addng.o art.o artio.o artsrch.o backpage.o bits.o cheat.o
obj2 = final.o head.o help.o init.o intrp.o kfile.o last.o $(NDIRO) ng.o
obj3 = ngdata.o ngsrch.o ngstuff.o only.o rcln.o rcstuff.o
obj4 = respond.o rn.o search.o sw.o term.o util.o

obj = $(obj1) $(obj2) $(obj3) $(obj4)

lintflags = -phbvxac

add1 = Makefile.old Pnews Pnews.header Rnmail art.help
add2 = bsd config.h config.sh eunice filexp
add3 = loc makedepend makedir mbox.saver myread newsetup
add4 = newsgroups newsnews ng.help norm.saver pager.help
add5 = pdp11 rn subs.help usg v7
add6 = grimble makedepend.out

addedbyconf = $(add1) $(add2) $(add3) $(add4) $(add5) $(add6)

# grrr
SHELL = /bin/sh
NROFF = tbl | nroff -man | col

.c.o:
	$(CC) -c $(CFLAGS) $*.c

all: $(public) $(private) $(util)
	touch all

rn: $(obj)
	$(CC) $(LDFLAGS) $(obj) $(libs) -o rn

# if a .h file depends on another .h file...
$(h):
	touch $@

install: rn
# won't work with csh
	export PATH || exit 1
	- chmod 755 makedir
	- ./makedir `./filexp $(rnbin)` 
	- mv $(rnbin)/rn $(rnbin)/rn.old
	- if test `pwd` != $(rnbin); then cp $(public) $(rnbin); fi
	cd $(rnbin); 
	- chmod 755 $(public)
	- ./makedir `./filexp $(rnlib)`
	- if test `pwd` != `./filexp $(rnlib)`; then cp INIT $(private) `./filexp $(rnlib)`; fi
	cd `./filexp $(rnlib)`; 
	- chmod 755 $(private)
	- if test ! -f `./filexp $(rnlib)/newsnews`; then cp newsnews `./filexp $(rnlib)`; fi
	- if test `pwd` != $(mansrc); then \
./makedir `./filexp $(mansrc)` ; \
for page in $(manpages); do \
cat $$page | $(NROFF) > $(mansrc)/`basename $$page .1`.$(manext); \
done; \
fi

clean:
	rm -f *.o 

realclean:
	rm -f rn *.o core $(addedbyconf) all

# The following lint has practically everything turned on.  Unfortunately,
# you have to wade through a lot of mumbo jumbo that can't be suppressed.
# If the source file has a /*NOSTRICT*/ somewhere, ignore the lint message
# for that spot.

lint:
	lint $(lintflags) $(defs) $(c) > rn.fuzz

depend:
	makedepend

# AUTOMATICALLY GENERATED MAKE DEPENDENCIES--PUT NOTHING BELOW THIS LINE
# If this runs make out of memory, delete /usr/include lines.
addng.o: /bsd43/usr/include/bsd43/bsd43_.h
addng.o: /bsd43/usr/include/bsd43/sys/fcntl.h
addng.o: /bsd43/usr/include/bsd43/sys/ttychars.h
addng.o: /bsd43/usr/include/bsd43/sys/ttydev.h
addng.o: /bsd43/usr/include/bsd43/sys/types.h
addng.o: /bsd43/usr/include/ctype.h
addng.o: /bsd43/usr/include/errno.h
addng.o: /bsd43/usr/include/fcntl.h
addng.o: /bsd43/usr/include/sgtty.h
addng.o: /bsd43/usr/include/signal.h
addng.o: /bsd43/usr/include/stdio.h
addng.o: /bsd43/usr/include/sys/ioctl.h
addng.o: /bsd43/usr/include/sys/stat.h
addng.o: /bsd43/usr/include/sys/types.h
addng.o: /bsd43/usr/include/sysv/sys/errno.h
addng.o: EXTERN.h
addng.o: INTERN.h
addng.o: addng.c
addng.o: addng.h
addng.o: common.h
addng.o: config.h
addng.o: intrp.h
addng.o: last.h
addng.o: ngdata.h
addng.o: only.h
addng.o: rcstuff.h
addng.o: rn.h
addng.o: search.h
addng.o: util.h
art.o: /bsd43/usr/include/bsd43/bsd43_.h
art.o: /bsd43/usr/include/bsd43/sys/fcntl.h
art.o: /bsd43/usr/include/bsd43/sys/ttychars.h
art.o: /bsd43/usr/include/bsd43/sys/ttydev.h
art.o: /bsd43/usr/include/bsd43/sys/types.h
art.o: /bsd43/usr/include/ctype.h
art.o: /bsd43/usr/include/errno.h
art.o: /bsd43/usr/include/fcntl.h
art.o: /bsd43/usr/include/sgtty.h
art.o: /bsd43/usr/include/signal.h
art.o: /bsd43/usr/include/stdio.h
art.o: /bsd43/usr/include/sys/ioctl.h
art.o: /bsd43/usr/include/sys/stat.h
art.o: /bsd43/usr/include/sys/types.h
art.o: /bsd43/usr/include/sysv/sys/errno.h
art.o: EXTERN.h
art.o: INTERN.h
art.o: art.c
art.o: art.h
art.o: artio.h
art.o: artstate.h
art.o: backpage.h
art.o: bits.h
art.o: cheat.h
art.o: common.h
art.o: config.h
art.o: final.h
art.o: head.h
art.o: help.h
art.o: intrp.h
art.o: ng.h
art.o: ngstuff.h
art.o: rcstuff.h
art.o: rn.h
art.o: search.h
art.o: sw.h
art.o: term.h
art.o: util.h
artio.o: /bsd43/usr/include/bsd43/bsd43_.h
artio.o: /bsd43/usr/include/bsd43/sys/fcntl.h
artio.o: /bsd43/usr/include/bsd43/sys/ttychars.h
artio.o: /bsd43/usr/include/bsd43/sys/ttydev.h
artio.o: /bsd43/usr/include/bsd43/sys/types.h
artio.o: /bsd43/usr/include/ctype.h
artio.o: /bsd43/usr/include/errno.h
artio.o: /bsd43/usr/include/fcntl.h
artio.o: /bsd43/usr/include/sgtty.h
artio.o: /bsd43/usr/include/signal.h
artio.o: /bsd43/usr/include/stdio.h
artio.o: /bsd43/usr/include/sys/ioctl.h
artio.o: /bsd43/usr/include/sys/stat.h
artio.o: /bsd43/usr/include/sys/types.h
artio.o: /bsd43/usr/include/sysv/sys/errno.h
artio.o: EXTERN.h
artio.o: INTERN.h
artio.o: artio.c
artio.o: artio.h
artio.o: common.h
artio.o: config.h
artsrch.o: /bsd43/usr/include/bsd43/bsd43_.h
artsrch.o: /bsd43/usr/include/bsd43/sys/fcntl.h
artsrch.o: /bsd43/usr/include/bsd43/sys/ttychars.h
artsrch.o: /bsd43/usr/include/bsd43/sys/ttydev.h
artsrch.o: /bsd43/usr/include/bsd43/sys/types.h
artsrch.o: /bsd43/usr/include/ctype.h
artsrch.o: /bsd43/usr/include/errno.h
artsrch.o: /bsd43/usr/include/fcntl.h
artsrch.o: /bsd43/usr/include/sgtty.h
artsrch.o: /bsd43/usr/include/signal.h
artsrch.o: /bsd43/usr/include/stdio.h
artsrch.o: /bsd43/usr/include/sys/ioctl.h
artsrch.o: /bsd43/usr/include/sys/stat.h
artsrch.o: /bsd43/usr/include/sys/types.h
artsrch.o: /bsd43/usr/include/sysv/sys/errno.h
artsrch.o: EXTERN.h
artsrch.o: INTERN.h
artsrch.o: artio.h
artsrch.o: artsrch.c
artsrch.o: artsrch.h
artsrch.o: bits.h
artsrch.o: cheat.h
artsrch.o: common.h
artsrch.o: config.h
artsrch.o: final.h
artsrch.o: head.h
artsrch.o: intrp.h
artsrch.o: kfile.h
artsrch.o: ng.h
artsrch.o: search.h
artsrch.o: term.h
artsrch.o: util.h
backpage.o: /bsd43/usr/include/bsd43/bsd43_.h
backpage.o: /bsd43/usr/include/bsd43/sys/fcntl.h
backpage.o: /bsd43/usr/include/bsd43/sys/ttychars.h
backpage.o: /bsd43/usr/include/bsd43/sys/ttydev.h
backpage.o: /bsd43/usr/include/bsd43/sys/types.h
backpage.o: /bsd43/usr/include/ctype.h
backpage.o: /bsd43/usr/include/errno.h
backpage.o: /bsd43/usr/include/fcntl.h
backpage.o: /bsd43/usr/include/sgtty.h
backpage.o: /bsd43/usr/include/signal.h
backpage.o: /bsd43/usr/include/stdio.h
backpage.o: /bsd43/usr/include/sys/ioctl.h
backpage.o: /bsd43/usr/include/sys/stat.h
backpage.o: /bsd43/usr/include/sys/types.h
backpage.o: /bsd43/usr/include/sysv/sys/errno.h
backpage.o: EXTERN.h
backpage.o: INTERN.h
backpage.o: backpage.c
backpage.o: backpage.h
backpage.o: common.h
backpage.o: config.h
backpage.o: final.h
backpage.o: intrp.h
bits.o: /bsd43/usr/include/bsd43/bsd43_.h
bits.o: /bsd43/usr/include/bsd43/sys/fcntl.h
bits.o: /bsd43/usr/include/bsd43/sys/ttychars.h
bits.o: /bsd43/usr/include/bsd43/sys/ttydev.h
bits.o: /bsd43/usr/include/bsd43/sys/types.h
bits.o: /bsd43/usr/include/ctype.h
bits.o: /bsd43/usr/include/errno.h
bits.o: /bsd43/usr/include/fcntl.h
bits.o: /bsd43/usr/include/sgtty.h
bits.o: /bsd43/usr/include/signal.h
bits.o: /bsd43/usr/include/stdio.h
bits.o: /bsd43/usr/include/sys/ioctl.h
bits.o: /bsd43/usr/include/sys/stat.h
bits.o: /bsd43/usr/include/sys/types.h
bits.o: /bsd43/usr/include/sysv/sys/errno.h
bits.o: EXTERN.h
bits.o: INTERN.h
bits.o: artio.h
bits.o: bits.c
bits.o: bits.h
bits.o: cheat.h
bits.o: common.h
bits.o: config.h
bits.o: final.h
bits.o: head.h
bits.o: intrp.h
bits.o: kfile.h
bits.o: ng.h
bits.o: ngdata.h
bits.o: rcln.h
bits.o: rcstuff.h
bits.o: rn.h
bits.o: util.h
cheat.o: /bsd43/usr/include/bsd43/bsd43_.h
cheat.o: /bsd43/usr/include/bsd43/sys/fcntl.h
cheat.o: /bsd43/usr/include/bsd43/sys/ttychars.h
cheat.o: /bsd43/usr/include/bsd43/sys/ttydev.h
cheat.o: /bsd43/usr/include/bsd43/sys/types.h
cheat.o: /bsd43/usr/include/ctype.h
cheat.o: /bsd43/usr/include/errno.h
cheat.o: /bsd43/usr/include/fcntl.h
cheat.o: /bsd43/usr/include/sgtty.h
cheat.o: /bsd43/usr/include/signal.h
cheat.o: /bsd43/usr/include/stdio.h
cheat.o: /bsd43/usr/include/sys/ioctl.h
cheat.o: /bsd43/usr/include/sys/stat.h
cheat.o: /bsd43/usr/include/sys/types.h
cheat.o: /bsd43/usr/include/sysv/sys/errno.h
cheat.o: EXTERN.h
cheat.o: INTERN.h
cheat.o: artio.h
cheat.o: artsrch.h
cheat.o: bits.h
cheat.o: cheat.c
cheat.o: cheat.h
cheat.o: common.h
cheat.o: config.h
cheat.o: head.h
cheat.o: intrp.h
cheat.o: ng.h
cheat.o: search.h
cheat.o: term.h
final.o: /bsd43/usr/include/bsd43/bsd43_.h
final.o: /bsd43/usr/include/bsd43/sys/fcntl.h
final.o: /bsd43/usr/include/bsd43/sys/ttychars.h
final.o: /bsd43/usr/include/bsd43/sys/ttydev.h
final.o: /bsd43/usr/include/bsd43/sys/types.h
final.o: /bsd43/usr/include/ctype.h
final.o: /bsd43/usr/include/errno.h
final.o: /bsd43/usr/include/fcntl.h
final.o: /bsd43/usr/include/sgtty.h
final.o: /bsd43/usr/include/signal.h
final.o: /bsd43/usr/include/stdio.h
final.o: /bsd43/usr/include/sys/ioctl.h
final.o: /bsd43/usr/include/sys/stat.h
final.o: /bsd43/usr/include/sys/types.h
final.o: /bsd43/usr/include/sysv/sys/errno.h
final.o: EXTERN.h
final.o: INTERN.h
final.o: bits.h
final.o: common.h
final.o: config.h
final.o: final.c
final.o: final.h
final.o: init.h
final.o: last.h
final.o: ng.h
final.o: rcstuff.h
final.o: term.h
final.o: util.h
head.o: /bsd43/usr/include/bsd43/bsd43_.h
head.o: /bsd43/usr/include/bsd43/sys/fcntl.h
head.o: /bsd43/usr/include/bsd43/sys/ttychars.h
head.o: /bsd43/usr/include/bsd43/sys/ttydev.h
head.o: /bsd43/usr/include/bsd43/sys/types.h
head.o: /bsd43/usr/include/ctype.h
head.o: /bsd43/usr/include/errno.h
head.o: /bsd43/usr/include/fcntl.h
head.o: /bsd43/usr/include/sgtty.h
head.o: /bsd43/usr/include/signal.h
head.o: /bsd43/usr/include/stdio.h
head.o: /bsd43/usr/include/sys/ioctl.h
head.o: /bsd43/usr/include/sys/stat.h
head.o: /bsd43/usr/include/sys/types.h
head.o: /bsd43/usr/include/sysv/sys/errno.h
head.o: EXTERN.h
head.o: INTERN.h
head.o: artio.h
head.o: bits.h
head.o: common.h
head.o: config.h
head.o: head.c
head.o: head.h
head.o: util.h
help.o: /bsd43/usr/include/bsd43/bsd43_.h
help.o: /bsd43/usr/include/bsd43/sys/fcntl.h
help.o: /bsd43/usr/include/bsd43/sys/ttychars.h
help.o: /bsd43/usr/include/bsd43/sys/ttydev.h
help.o: /bsd43/usr/include/bsd43/sys/types.h
help.o: /bsd43/usr/include/ctype.h
help.o: /bsd43/usr/include/errno.h
help.o: /bsd43/usr/include/fcntl.h
help.o: /bsd43/usr/include/sgtty.h
help.o: /bsd43/usr/include/signal.h
help.o: /bsd43/usr/include/stdio.h
help.o: /bsd43/usr/include/sys/ioctl.h
help.o: /bsd43/usr/include/sys/stat.h
help.o: /bsd43/usr/include/sys/types.h
help.o: /bsd43/usr/include/sysv/sys/errno.h
help.o: EXTERN.h
help.o: INTERN.h
help.o: common.h
help.o: config.h
help.o: help.c
help.o: help.h
help.o: rn.h
help.o: term.h
init.o: /bsd43/usr/include/bsd43/bsd43_.h
init.o: /bsd43/usr/include/bsd43/sys/fcntl.h
init.o: /bsd43/usr/include/bsd43/sys/ttychars.h
init.o: /bsd43/usr/include/bsd43/sys/ttydev.h
init.o: /bsd43/usr/include/bsd43/sys/types.h
init.o: /bsd43/usr/include/ctype.h
init.o: /bsd43/usr/include/errno.h
init.o: /bsd43/usr/include/fcntl.h
init.o: /bsd43/usr/include/sgtty.h
init.o: /bsd43/usr/include/signal.h
init.o: /bsd43/usr/include/stdio.h
init.o: /bsd43/usr/include/sys/ioctl.h
init.o: /bsd43/usr/include/sys/stat.h
init.o: /bsd43/usr/include/sys/types.h
init.o: /bsd43/usr/include/sysv/sys/errno.h
init.o: EXTERN.h
init.o: INTERN.h
init.o: addng.h
init.o: art.h
init.o: artio.h
init.o: artsrch.h
init.o: backpage.h
init.o: bits.h
init.o: cheat.h
init.o: common.h
init.o: config.h
init.o: final.h
init.o: head.h
init.o: help.h
init.o: init.c
init.o: init.h
init.o: intrp.h
init.o: kfile.h
init.o: last.h
init.o: ng.h
init.o: ngdata.h
init.o: ngsrch.h
init.o: ngstuff.h
init.o: only.h
init.o: rcln.h
init.o: rcstuff.h
init.o: respond.h
init.o: rn.h
init.o: search.h
init.o: sw.h
init.o: term.h
init.o: util.h
intrp.o: /bsd43/usr/include/bsd43/bsd43_.h
intrp.o: /bsd43/usr/include/bsd43/sys/fcntl.h
intrp.o: /bsd43/usr/include/bsd43/sys/ttychars.h
intrp.o: /bsd43/usr/include/bsd43/sys/ttydev.h
intrp.o: /bsd43/usr/include/bsd43/sys/types.h
intrp.o: /bsd43/usr/include/ctype.h
intrp.o: /bsd43/usr/include/errno.h
intrp.o: /bsd43/usr/include/fcntl.h
intrp.o: /bsd43/usr/include/sgtty.h
intrp.o: /bsd43/usr/include/signal.h
intrp.o: /bsd43/usr/include/stdio.h
intrp.o: /bsd43/usr/include/sys/ioctl.h
intrp.o: /bsd43/usr/include/sys/stat.h
intrp.o: /bsd43/usr/include/sys/types.h
intrp.o: /bsd43/usr/include/sysv/sys/errno.h
intrp.o: EXTERN.h
intrp.o: INTERN.h
intrp.o: artio.h
intrp.o: artsrch.h
intrp.o: bits.h
intrp.o: common.h
intrp.o: config.h
intrp.o: final.h
intrp.o: head.h
intrp.o: intrp.c
intrp.o: intrp.h
intrp.o: ng.h
intrp.o: rcstuff.h
intrp.o: respond.h
intrp.o: rn.h
intrp.o: search.h
intrp.o: term.h
intrp.o: util.h
kfile.o: /bsd43/usr/include/bsd43/bsd43_.h
kfile.o: /bsd43/usr/include/bsd43/sys/fcntl.h
kfile.o: /bsd43/usr/include/bsd43/sys/ttychars.h
kfile.o: /bsd43/usr/include/bsd43/sys/ttydev.h
kfile.o: /bsd43/usr/include/bsd43/sys/types.h
kfile.o: /bsd43/usr/include/ctype.h
kfile.o: /bsd43/usr/include/errno.h
kfile.o: /bsd43/usr/include/fcntl.h
kfile.o: /bsd43/usr/include/sgtty.h
kfile.o: /bsd43/usr/include/signal.h
kfile.o: /bsd43/usr/include/stdio.h
kfile.o: /bsd43/usr/include/sys/ioctl.h
kfile.o: /bsd43/usr/include/sys/stat.h
kfile.o: /bsd43/usr/include/sys/types.h
kfile.o: /bsd43/usr/include/sysv/sys/errno.h
kfile.o: EXTERN.h
kfile.o: INTERN.h
kfile.o: artsrch.h
kfile.o: bits.h
kfile.o: common.h
kfile.o: config.h
kfile.o: intrp.h
kfile.o: kfile.c
kfile.o: kfile.h
kfile.o: ng.h
kfile.o: ngstuff.h
kfile.o: rcstuff.h
kfile.o: rn.h
kfile.o: search.h
kfile.o: term.h
kfile.o: util.h
kitlists.o: /bsd43/usr/include/bsd43/bsd43_.h
kitlists.o: /bsd43/usr/include/stdio.h
kitlists.o: kitlists.c
last.o: /bsd43/usr/include/bsd43/bsd43_.h
last.o: /bsd43/usr/include/bsd43/sys/fcntl.h
last.o: /bsd43/usr/include/bsd43/sys/ttychars.h
last.o: /bsd43/usr/include/bsd43/sys/ttydev.h
last.o: /bsd43/usr/include/bsd43/sys/types.h
last.o: /bsd43/usr/include/ctype.h
last.o: /bsd43/usr/include/errno.h
last.o: /bsd43/usr/include/fcntl.h
last.o: /bsd43/usr/include/sgtty.h
last.o: /bsd43/usr/include/signal.h
last.o: /bsd43/usr/include/stdio.h
last.o: /bsd43/usr/include/sys/ioctl.h
last.o: /bsd43/usr/include/sys/stat.h
last.o: /bsd43/usr/include/sys/types.h
last.o: /bsd43/usr/include/sysv/sys/errno.h
last.o: EXTERN.h
last.o: INTERN.h
last.o: common.h
last.o: config.h
last.o: intrp.h
last.o: last.c
last.o: last.h
last.o: rn.h
last.o: util.h
ndir.o: /bsd43/usr/include/bsd43/bsd43_.h
ndir.o: /bsd43/usr/include/bsd43/sys/fcntl.h
ndir.o: /bsd43/usr/include/bsd43/sys/ttychars.h
ndir.o: /bsd43/usr/include/bsd43/sys/ttydev.h
ndir.o: /bsd43/usr/include/bsd43/sys/types.h
ndir.o: /bsd43/usr/include/ctype.h
ndir.o: /bsd43/usr/include/errno.h
ndir.o: /bsd43/usr/include/fcntl.h
ndir.o: /bsd43/usr/include/sgtty.h
ndir.o: /bsd43/usr/include/signal.h
ndir.o: /bsd43/usr/include/stdio.h
ndir.o: /bsd43/usr/include/sys/dir.h
ndir.o: /bsd43/usr/include/sys/ioctl.h
ndir.o: /bsd43/usr/include/sys/stat.h
ndir.o: /bsd43/usr/include/sys/types.h
ndir.o: /bsd43/usr/include/sysv/sys/errno.h
ndir.o: EXTERN.h
ndir.o: INTERN.h
ndir.o: common.h
ndir.o: config.h
ndir.o: ndir.c
ndir.o: ndir.h
ng.o: /bsd43/usr/include/bsd43/bsd43_.h
ng.o: /bsd43/usr/include/bsd43/sys/fcntl.h
ng.o: /bsd43/usr/include/bsd43/sys/ttychars.h
ng.o: /bsd43/usr/include/bsd43/sys/ttydev.h
ng.o: /bsd43/usr/include/bsd43/sys/types.h
ng.o: /bsd43/usr/include/ctype.h
ng.o: /bsd43/usr/include/errno.h
ng.o: /bsd43/usr/include/fcntl.h
ng.o: /bsd43/usr/include/sgtty.h
ng.o: /bsd43/usr/include/signal.h
ng.o: /bsd43/usr/include/stdio.h
ng.o: /bsd43/usr/include/sys/ioctl.h
ng.o: /bsd43/usr/include/sys/stat.h
ng.o: /bsd43/usr/include/sys/types.h
ng.o: /bsd43/usr/include/sysv/sys/errno.h
ng.o: EXTERN.h
ng.o: INTERN.h
ng.o: art.h
ng.o: artio.h
ng.o: artsrch.h
ng.o: artstate.h
ng.o: backpage.h
ng.o: bits.h
ng.o: cheat.h
ng.o: common.h
ng.o: config.h
ng.o: final.h
ng.o: head.h
ng.o: help.h
ng.o: intrp.h
ng.o: kfile.h
ng.o: last.h
ng.o: ng.c
ng.o: ng.h
ng.o: ngdata.h
ng.o: ngstuff.h
ng.o: rcln.h
ng.o: rcstuff.h
ng.o: respond.h
ng.o: rn.h
ng.o: search.h
ng.o: term.h
ng.o: util.h
ngdata.o: /bsd43/usr/include/bsd43/bsd43_.h
ngdata.o: /bsd43/usr/include/bsd43/sys/fcntl.h
ngdata.o: /bsd43/usr/include/bsd43/sys/ttychars.h
ngdata.o: /bsd43/usr/include/bsd43/sys/ttydev.h
ngdata.o: /bsd43/usr/include/bsd43/sys/types.h
ngdata.o: /bsd43/usr/include/ctype.h
ngdata.o: /bsd43/usr/include/errno.h
ngdata.o: /bsd43/usr/include/fcntl.h
ngdata.o: /bsd43/usr/include/sgtty.h
ngdata.o: /bsd43/usr/include/signal.h
ngdata.o: /bsd43/usr/include/stdio.h
ngdata.o: /bsd43/usr/include/sys/dir.h
ngdata.o: /bsd43/usr/include/sys/ioctl.h
ngdata.o: /bsd43/usr/include/sys/stat.h
ngdata.o: /bsd43/usr/include/sys/types.h
ngdata.o: /bsd43/usr/include/sysv/sys/errno.h
ngdata.o: EXTERN.h
ngdata.o: INTERN.h
ngdata.o: common.h
ngdata.o: config.h
ngdata.o: final.h
ngdata.o: intrp.h
ngdata.o: ndir.h
ngdata.o: ngdata.c
ngdata.o: ngdata.h
ngdata.o: rcln.h
ngdata.o: rcstuff.h
ngdata.o: rn.h
ngsrch.o: /bsd43/usr/include/bsd43/bsd43_.h
ngsrch.o: /bsd43/usr/include/bsd43/sys/fcntl.h
ngsrch.o: /bsd43/usr/include/bsd43/sys/ttychars.h
ngsrch.o: /bsd43/usr/include/bsd43/sys/ttydev.h
ngsrch.o: /bsd43/usr/include/bsd43/sys/types.h
ngsrch.o: /bsd43/usr/include/ctype.h
ngsrch.o: /bsd43/usr/include/errno.h
ngsrch.o: /bsd43/usr/include/fcntl.h
ngsrch.o: /bsd43/usr/include/sgtty.h
ngsrch.o: /bsd43/usr/include/signal.h
ngsrch.o: /bsd43/usr/include/stdio.h
ngsrch.o: /bsd43/usr/include/sys/ioctl.h
ngsrch.o: /bsd43/usr/include/sys/stat.h
ngsrch.o: /bsd43/usr/include/sys/types.h
ngsrch.o: /bsd43/usr/include/sysv/sys/errno.h
ngsrch.o: EXTERN.h
ngsrch.o: INTERN.h
ngsrch.o: common.h
ngsrch.o: config.h
ngsrch.o: final.h
ngsrch.o: ngsrch.c
ngsrch.o: ngsrch.h
ngsrch.o: rcln.h
ngsrch.o: rcstuff.h
ngsrch.o: rn.h
ngsrch.o: search.h
ngsrch.o: term.h
ngsrch.o: util.h
ngstuff.o: /bsd43/usr/include/bsd43/bsd43_.h
ngstuff.o: /bsd43/usr/include/bsd43/sys/fcntl.h
ngstuff.o: /bsd43/usr/include/bsd43/sys/ttychars.h
ngstuff.o: /bsd43/usr/include/bsd43/sys/ttydev.h
ngstuff.o: /bsd43/usr/include/bsd43/sys/types.h
ngstuff.o: /bsd43/usr/include/ctype.h
ngstuff.o: /bsd43/usr/include/errno.h
ngstuff.o: /bsd43/usr/include/fcntl.h
ngstuff.o: /bsd43/usr/include/sgtty.h
ngstuff.o: /bsd43/usr/include/signal.h
ngstuff.o: /bsd43/usr/include/stdio.h
ngstuff.o: /bsd43/usr/include/sys/ioctl.h
ngstuff.o: /bsd43/usr/include/sys/stat.h
ngstuff.o: /bsd43/usr/include/sys/types.h
ngstuff.o: /bsd43/usr/include/sysv/sys/errno.h
ngstuff.o: EXTERN.h
ngstuff.o: INTERN.h
ngstuff.o: bits.h
ngstuff.o: cheat.h
ngstuff.o: common.h
ngstuff.o: config.h
ngstuff.o: final.h
ngstuff.o: head.h
ngstuff.o: intrp.h
ngstuff.o: ng.h
ngstuff.o: ngstuff.c
ngstuff.o: ngstuff.h
ngstuff.o: sw.h
ngstuff.o: term.h
ngstuff.o: util.h
only.o: /bsd43/usr/include/bsd43/bsd43_.h
only.o: /bsd43/usr/include/bsd43/sys/fcntl.h
only.o: /bsd43/usr/include/bsd43/sys/ttychars.h
only.o: /bsd43/usr/include/bsd43/sys/ttydev.h
only.o: /bsd43/usr/include/bsd43/sys/types.h
only.o: /bsd43/usr/include/ctype.h
only.o: /bsd43/usr/include/errno.h
only.o: /bsd43/usr/include/fcntl.h
only.o: /bsd43/usr/include/sgtty.h
only.o: /bsd43/usr/include/signal.h
only.o: /bsd43/usr/include/stdio.h
only.o: /bsd43/usr/include/sys/ioctl.h
only.o: /bsd43/usr/include/sys/stat.h
only.o: /bsd43/usr/include/sys/types.h
only.o: /bsd43/usr/include/sysv/sys/errno.h
only.o: EXTERN.h
only.o: INTERN.h
only.o: common.h
only.o: config.h
only.o: final.h
only.o: ngsrch.h
only.o: only.c
only.o: only.h
only.o: search.h
only.o: util.h
rcln.o: /bsd43/usr/include/bsd43/bsd43_.h
rcln.o: /bsd43/usr/include/bsd43/sys/fcntl.h
rcln.o: /bsd43/usr/include/bsd43/sys/ttychars.h
rcln.o: /bsd43/usr/include/bsd43/sys/ttydev.h
rcln.o: /bsd43/usr/include/bsd43/sys/types.h
rcln.o: /bsd43/usr/include/ctype.h
rcln.o: /bsd43/usr/include/errno.h
rcln.o: /bsd43/usr/include/fcntl.h
rcln.o: /bsd43/usr/include/sgtty.h
rcln.o: /bsd43/usr/include/signal.h
rcln.o: /bsd43/usr/include/stdio.h
rcln.o: /bsd43/usr/include/sys/ioctl.h
rcln.o: /bsd43/usr/include/sys/stat.h
rcln.o: /bsd43/usr/include/sys/types.h
rcln.o: /bsd43/usr/include/sysv/sys/errno.h
rcln.o: EXTERN.h
rcln.o: INTERN.h
rcln.o: common.h
rcln.o: config.h
rcln.o: ngdata.h
rcln.o: rcln.c
rcln.o: rcln.h
rcln.o: rcstuff.h
rcln.o: util.h
rcstuff.o: /bsd43/usr/include/bsd43/bsd43_.h
rcstuff.o: /bsd43/usr/include/bsd43/sys/fcntl.h
rcstuff.o: /bsd43/usr/include/bsd43/sys/ttychars.h
rcstuff.o: /bsd43/usr/include/bsd43/sys/ttydev.h
rcstuff.o: /bsd43/usr/include/bsd43/sys/types.h
rcstuff.o: /bsd43/usr/include/ctype.h
rcstuff.o: /bsd43/usr/include/errno.h
rcstuff.o: /bsd43/usr/include/fcntl.h
rcstuff.o: /bsd43/usr/include/sgtty.h
rcstuff.o: /bsd43/usr/include/signal.h
rcstuff.o: /bsd43/usr/include/stdio.h
rcstuff.o: /bsd43/usr/include/sys/ioctl.h
rcstuff.o: /bsd43/usr/include/sys/stat.h
rcstuff.o: /bsd43/usr/include/sys/types.h
rcstuff.o: /bsd43/usr/include/sysv/sys/errno.h
rcstuff.o: EXTERN.h
rcstuff.o: INTERN.h
rcstuff.o: common.h
rcstuff.o: config.h
rcstuff.o: final.h
rcstuff.o: intrp.h
rcstuff.o: ngdata.h
rcstuff.o: only.h
rcstuff.o: rcln.h
rcstuff.o: rcstuff.c
rcstuff.o: rcstuff.h
rcstuff.o: rn.h
rcstuff.o: search.h
rcstuff.o: term.h
rcstuff.o: util.h
respond.o: /bsd43/usr/include/bsd43/bsd43_.h
respond.o: /bsd43/usr/include/bsd43/sys/fcntl.h
respond.o: /bsd43/usr/include/bsd43/sys/ttychars.h
respond.o: /bsd43/usr/include/bsd43/sys/ttydev.h
respond.o: /bsd43/usr/include/bsd43/sys/types.h
respond.o: /bsd43/usr/include/ctype.h
respond.o: /bsd43/usr/include/errno.h
respond.o: /bsd43/usr/include/fcntl.h
respond.o: /bsd43/usr/include/sgtty.h
respond.o: /bsd43/usr/include/signal.h
respond.o: /bsd43/usr/include/stdio.h
respond.o: /bsd43/usr/include/sys/ioctl.h
respond.o: /bsd43/usr/include/sys/stat.h
respond.o: /bsd43/usr/include/sys/types.h
respond.o: /bsd43/usr/include/sysv/sys/errno.h
respond.o: EXTERN.h
respond.o: INTERN.h
respond.o: artio.h
respond.o: common.h
respond.o: config.h
respond.o: final.h
respond.o: head.h
respond.o: intrp.h
respond.o: ng.h
respond.o: respond.c
respond.o: respond.h
respond.o: rn.h
respond.o: term.h
respond.o: util.h
rn.o: /bsd43/usr/include/bsd43/bsd43_.h
rn.o: /bsd43/usr/include/bsd43/sys/fcntl.h
rn.o: /bsd43/usr/include/bsd43/sys/ttychars.h
rn.o: /bsd43/usr/include/bsd43/sys/ttydev.h
rn.o: /bsd43/usr/include/bsd43/sys/types.h
rn.o: /bsd43/usr/include/ctype.h
rn.o: /bsd43/usr/include/errno.h
rn.o: /bsd43/usr/include/fcntl.h
rn.o: /bsd43/usr/include/sgtty.h
rn.o: /bsd43/usr/include/signal.h
rn.o: /bsd43/usr/include/stdio.h
rn.o: /bsd43/usr/include/sys/ioctl.h
rn.o: /bsd43/usr/include/sys/stat.h
rn.o: /bsd43/usr/include/sys/types.h
rn.o: /bsd43/usr/include/sysv/sys/errno.h
rn.o: EXTERN.h
rn.o: INTERN.h
rn.o: addng.h
rn.o: common.h
rn.o: config.h
rn.o: final.h
rn.o: help.h
rn.o: init.h
rn.o: intrp.h
rn.o: last.h
rn.o: ng.h
rn.o: ngdata.h
rn.o: ngsrch.h
rn.o: only.h
rn.o: rcln.h
rn.o: rcstuff.h
rn.o: rn.c
rn.o: rn.h
rn.o: search.h
rn.o: sw.h
rn.o: term.h
rn.o: util.h
search.o: /bsd43/usr/include/bsd43/bsd43_.h
search.o: /bsd43/usr/include/bsd43/sys/fcntl.h
search.o: /bsd43/usr/include/bsd43/sys/ttychars.h
search.o: /bsd43/usr/include/bsd43/sys/ttydev.h
search.o: /bsd43/usr/include/bsd43/sys/types.h
search.o: /bsd43/usr/include/ctype.h
search.o: /bsd43/usr/include/errno.h
search.o: /bsd43/usr/include/fcntl.h
search.o: /bsd43/usr/include/sgtty.h
search.o: /bsd43/usr/include/signal.h
search.o: /bsd43/usr/include/stdio.h
search.o: /bsd43/usr/include/sys/ioctl.h
search.o: /bsd43/usr/include/sys/stat.h
search.o: /bsd43/usr/include/sys/types.h
search.o: /bsd43/usr/include/sysv/sys/errno.h
search.o: EXTERN.h
search.o: INTERN.h
search.o: common.h
search.o: config.h
search.o: search.c
search.o: search.h
search.o: util.h
sw.o: /bsd43/usr/include/bsd43/bsd43_.h
sw.o: /bsd43/usr/include/bsd43/sys/fcntl.h
sw.o: /bsd43/usr/include/bsd43/sys/ttychars.h
sw.o: /bsd43/usr/include/bsd43/sys/ttydev.h
sw.o: /bsd43/usr/include/bsd43/sys/types.h
sw.o: /bsd43/usr/include/ctype.h
sw.o: /bsd43/usr/include/errno.h
sw.o: /bsd43/usr/include/fcntl.h
sw.o: /bsd43/usr/include/sgtty.h
sw.o: /bsd43/usr/include/signal.h
sw.o: /bsd43/usr/include/stdio.h
sw.o: /bsd43/usr/include/sys/ioctl.h
sw.o: /bsd43/usr/include/sys/stat.h
sw.o: /bsd43/usr/include/sys/types.h
sw.o: /bsd43/usr/include/sysv/sys/errno.h
sw.o: EXTERN.h
sw.o: INTERN.h
sw.o: common.h
sw.o: config.h
sw.o: head.h
sw.o: intrp.h
sw.o: ng.h
sw.o: only.h
sw.o: search.h
sw.o: sw.c
sw.o: sw.h
sw.o: term.h
sw.o: util.h
term.o: /bsd43/usr/include/bsd43/bsd43_.h
term.o: /bsd43/usr/include/bsd43/sys/fcntl.h
term.o: /bsd43/usr/include/bsd43/sys/ttychars.h
term.o: /bsd43/usr/include/bsd43/sys/ttydev.h
term.o: /bsd43/usr/include/bsd43/sys/types.h
term.o: /bsd43/usr/include/ctype.h
term.o: /bsd43/usr/include/errno.h
term.o: /bsd43/usr/include/fcntl.h
term.o: /bsd43/usr/include/sgtty.h
term.o: /bsd43/usr/include/signal.h
term.o: /bsd43/usr/include/stdio.h
term.o: /bsd43/usr/include/sys/ioctl.h
term.o: /bsd43/usr/include/sys/stat.h
term.o: /bsd43/usr/include/sys/types.h
term.o: /bsd43/usr/include/sysv/sys/errno.h
term.o: EXTERN.h
term.o: INTERN.h
term.o: cheat.h
term.o: common.h
term.o: config.h
term.o: final.h
term.o: help.h
term.o: intrp.h
term.o: term.c
term.o: term.h
term.o: util.h
util.o: /bsd43/usr/include/bsd43/bsd43_.h
util.o: /bsd43/usr/include/bsd43/sys/fcntl.h
util.o: /bsd43/usr/include/bsd43/sys/ttychars.h
util.o: /bsd43/usr/include/bsd43/sys/ttydev.h
util.o: /bsd43/usr/include/bsd43/sys/types.h
util.o: /bsd43/usr/include/ctype.h
util.o: /bsd43/usr/include/errno.h
util.o: /bsd43/usr/include/fcntl.h
util.o: /bsd43/usr/include/sgtty.h
util.o: /bsd43/usr/include/signal.h
util.o: /bsd43/usr/include/stdio.h
util.o: /bsd43/usr/include/sys/dir.h
util.o: /bsd43/usr/include/sys/ioctl.h
util.o: /bsd43/usr/include/sys/stat.h
util.o: /bsd43/usr/include/sys/types.h
util.o: /bsd43/usr/include/sysv/sys/errno.h
util.o: EXTERN.h
util.o: INTERN.h
util.o: common.h
util.o: config.h
util.o: final.h
util.o: ndir.h
util.o: util.c
util.o: util.h
Makefile: Makefile.SH config.sh ; /bin/sh Makefile.SH
Pnews: Pnews.SH config.sh ; /bin/sh Pnews.SH
Rnmail: Rnmail.SH config.sh ; /bin/sh Rnmail.SH
art.help: art.help.SH config.sh ; /bin/sh art.help.SH
makedepend: makedepend.SH config.sh ; /bin/sh makedepend.SH
makedir: makedir.SH config.sh ; /bin/sh makedir.SH
mbox.saver: mbox.saver.SH config.sh ; /bin/sh mbox.saver.SH
newsetup: newsetup.SH config.sh ; /bin/sh newsetup.SH
newsgroups: newsgroups.SH config.sh ; /bin/sh newsgroups.SH
newsnews: newsnews.SH config.sh ; /bin/sh newsnews.SH
ng.help: ng.help.SH config.sh ; /bin/sh ng.help.SH
norm.saver: norm.saver.SH config.sh ; /bin/sh norm.saver.SH
pager.help: pager.help.SH config.sh ; /bin/sh pager.help.SH
subs.help: subs.help.SH config.sh ; /bin/sh subs.help.SH
# WARNING: Put nothing here or make depend will gobble it up!
